### ISSUE TITLE
Which level should we analyze for ground truth generation in salami?

### ISSUE THREAD

**Issue by bmcfee** [urinieto/similarity_classification#1]
Functions, large, or small?

Functions and large typically have the same boundaries, and should give the same (general) results/alignment scores.  The difference between these two will then boil down to computing the cost threshold.

Small vs large is an interesting question.  Potentially, it could give us more example paths to work with.  Any repetition in large should also occur in small, but not vice versa, since large would rule out repetitions within a single large component.

Should we do all of the above?

**Comment by urinieto** [comment]
It's indeed an interesting point. I say we should do both, so that we have
a larger space to explore.

**Comment by bmcfee** [comment]
I wrote a little script to crunch out the results in pandas.  Check it out [here](http://nbviewer.ipython.org/github/urinieto/similarity_classification/blob/fa8f174e78b7f283a190ae2a838966eb9f1ece1f/notes/Repetition%20detection%20threshold.ipynb) (cell 11).

The tldr: dtw using correlation and no length normalization gets the best F scores across the board.

**Comment by urinieto** [comment]
Sweet. Ok, scores with paths for the large scale segments are computed and
uploaded. They seem to contain the right info now. Will do the small scale
ones now.

**Comment by bmcfee** [comment]
Updated the notebook with the new scores; results are [here](http://nbviewer.ipython.org/github/urinieto/similarity_classification/blob/ffdab7b351ce907051fedc0a343dfb3cbbd23b57/notes/Repetition%20detection%20threshold.ipynb) (cell 12).  Now with plots!

It's a mixed bag.  For functions, l1/l2 are clearly better than correlation, but the results switch for large and small.  Normalization is still the same though: none is best.

**Comment by urinieto** [comment]
This means that for the Isophonics data, L1/L2 is better than correlation,
but for SALAMI, the correlation distance seems to work best.

So, I propose to fix the normalization technique to "none", and train two
models for each dataset: one with L2 and the other with correlation. And
then see which one works best. What do you think?

What do you want me to do at this point?

**Comment by bmcfee** [comment]
> This means that for the Isophonics data, L1/L2 is better than correlation,
> but for SALAMI, the correlation distance seems to work best.

Right.  Do you think we'd get different results for salami.functions?  The boundaries are the same as salami.large, but the label agreement might be different.

**Comment by urinieto** [comment]
oh, I thought the labels would be exactly the same in terms of uniqueness. I'm gonna compute the salami functions to see what's up.

In any case, we should, at least, train these models (dataset, level, distance, normalization):
- SALAMI, large_scale, L2, none
- SALAMI, large_scale, correlation, none
- SALAMI, small_scale, L2, none
- SALAMI, small_scale, correlation, none
- Isophonics, function, L2, none
- Isophonics, function, correlation, none

**Comment by bmcfee** [comment]
Maybe we should also include salami second annotators?

**Comment by urinieto** [comment]
Mmmh I suggest to just take the second annotators once we narrow down
whether we need large/small/function and L1/correlation, and just to
explore the impact of the annotators used (and then we could go into a
paragraph or two talking about subjectivity).

**Comment by urinieto** [comment]
The features can be downloaded from here:
https://www.dropbox.com/s/50xvfiixge4tum1/dtw_features.tar.gz?dl=0

The rest of the scores and paths for the SALAMI "function" are being computed now (I thought I had done that, but apparently I didn't), will be ready tomorrow morning.

**Comment by urinieto** [comment]
Alright, the scores and paths for SALAMI "function" should be in the data folder now (it was faster than I thought).

**Comment by bmcfee** [comment]
New results:

```
                                       hmean    max    min   none
scale                     metric                                 
Isophonics_level_function L1           0.772  0.779  0.774  0.927
                          L2           0.738  0.724  0.747  0.924
                          correlation  0.792  0.775  0.813  0.868

SALAMI_level_function     L1           0.720  0.673  0.724  0.774
                          L2           0.710  0.657  0.716  0.774
                          correlation  0.716  0.669  0.721  0.758

SALAMI_level_large_scale  L1           0.724  0.694  0.729  0.762
                          L2           0.726  0.690  0.728  0.763
                          correlation  0.741  0.713  0.745  0.788

SALAMI_level_small_scale  L1           0.596  0.581  0.597  0.605
                          L2           0.597  0.581  0.599  0.605
                          correlation  0.640  0.619  0.636  0.650
```

**Comment by urinieto** [comment]
So, it seems like the correlation distance is only better for the large and
small scales, while L1 or L2 is better for the functions.

Given that the correlation distance yields slightly better results for the
large scale (78.8), I might use that instead of using L2 for the SALAMI
function (77.4).

What do you think?

**Comment by bmcfee** [comment]
For completeness, here are the stats after dropping all samples with `f_score < 0.5`:

```
                                       hmean    max    min   none
scale                     metric                                 
Isophonics_level_function L1           0.778  0.783  0.779  0.936
                          L2           0.744  0.727  0.752  0.934
                          correlation  0.815  0.780  0.836  0.895

SALAMI_level_function     L1           0.741  0.694  0.751  0.824
                          L2           0.734  0.680  0.744  0.827
                          correlation  0.750  0.704  0.764  0.820

SALAMI_level_large_scale  L1           0.749  0.714  0.755  0.790
                          L2           0.748  0.707  0.752  0.788
                          correlation  0.764  0.735  0.769  0.813

SALAMI_level_small_scale  L1           0.696  0.674  0.702  0.717
                          L2           0.697  0.671  0.704  0.716
                          correlation  0.725  0.698  0.725  0.742
```

**Comment by urinieto** [comment]
mmmmhh maybe we should only focus on the function levels?
