### ISSUE TITLE
Taking forever to compute + .pk files too large?

### ISSUE THREAD

**Issue by urinieto** [urinieto/similarity_classification#3]
I have been re-computing the scores, and now I am including the paths, the thresholds, and the f-measures. However, it takes a long time to compute (around 6 or 7 hours each file), and each file weights around ~800MB (my guess is that the Isophonics ones will be much lighter).

I believe the files weight so much because I am saving the paths in a list of lists, which is highly inefficient (and it contains redundant information, since the matrices are symmetrical). When I tgz them, the files become around 25MB each, which is not that bad.

Should we stop and re-run the scores, or should we leave them like this? I got 2 files so far (of 12).

**Comment by urinieto** [comment]
SALAMI small scale files are around 3.7GB, which is unacceptable.

**Comment by bmcfee** [comment]
Hrm.  A couple of simple hacks come to mind:
- Cast everything down to float32
- Use `pickle.dump(..., protocol=-1)` to use the latest protocol

The segment-by-segment cost matrix probably doesn't cost too much to store.

The segment-by-segment path arrays might be hurting here, in which case, yeah, only store the upper triangle.

**Comment by urinieto** [comment]
After doing that, the files are dramatically reduced (now the largest file is no more than 2MB,  which is so small that makes me wonder if I'm doing something wrong).

Only one more file remaining to be computed, once all of them are done I will upload them to the data folder.

**Comment by urinieto** [comment]
Ok, I just uploaded the data. Please, take a look at it if you have some time, and let me know if it makes sense.

**Comment by urinieto** [comment]
Ok, the small scale data is uploaded. I think all scores and paths are correct now.
